apiVersion: v1 # versão da API do Kubernetes
kind: Pod # tipo do objeto que estamos criando
metadata: # metadados do Pod 
  name: girus # nome do Pod que estamos criando
  labels: # labels do Pod
    run: giropops # label run com o valor giropops
    service: webserver
spec: # especificação do Pod
  containers: # containers que estão dentro do Pod
  - name: girus # nome do container
    image: nginx # imagem do container
    resources: {}
  - name: apache
    image: httpd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
